package com.avicsafety.ShenYangTowerComService.PowerManager.push;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "POSITION_BEAN".
 */
public class PositionBean {

    private Long id;//id
    private String Pid;//工单id
    private String startTime;//发电工单预计开始时间
    private String endTime;//发电工单预计结束时间
    private String thenTime;//接单时间
    private String endDate;//结束工单时间
    private String type;//工单类型

    public PositionBean() {
    }

    public PositionBean(Long id) {
        this.id = id;
    }

    public PositionBean(Long id, String Pid, String startTime, String endTime, String thenTime, String endDate, String type) {
        this.id = id;
        this.Pid = Pid;
        this.startTime = startTime;
        this.endTime = endTime;
        this.thenTime = thenTime;
        this.endDate = endDate;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPid() {
        return Pid;
    }

    public void setPid(String Pid) {
        this.Pid = Pid;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public String getThenTime() {
        return thenTime;
    }

    public void setThenTime(String thenTime) {
        this.thenTime = thenTime;
    }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
